[tools]
1password = "latest"
"aqua:boyter/scc" = "latest"
"aqua:docker/buildx" = "latest"
"aqua:docker/cli" = "latest"
"aqua:docker/compose" = "latest"
"aqua:g-plane/pnpm-shell-completion" = "latest"
"aqua:k1LoW/gh-do" = "latest"
"aqua:rossmacarthur/sheldon" = "latest"
"aqua:sharkdp/pastel" = "latest"
"aqua:ymtdzzz/otel-tui" = "latest"
ast-grep = "latest"
bat = "latest"
bun = "1.3.5"
chezmoi = "latest"
colima = "latest"
delta = "latest"
deno = "2.6.3"
dive = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
"github:k1LoW/git-wt" = "latest"
"github:zyedidia/micro" = "latest"
hyperfine = "latest"
jq = "latest"
lima = "latest"
lsd = "latest"
node = "lts"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@mizchi/lsmcp" = "latest"
"npm:ccusage" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
pinact = "latest"
ripgrep = "latest"
usage = "latest"
yq = "latest"

[settings]
lockfile = true
experimental = true
